#!/bin/bash
git add .
echo "Commit Message:"
read commit_message
git commit -m "$commit_message"
result=$?

int i;
(i = 0);
str=$result
while (str[i] != '\0')
{
    if (str[i] == ' ')
    {
        str[i] = '_';
    }
    i++;
    $result = str

    if [ $result -eq 0 ]; then
        git push
    else
        echo "Commit Failed"
}
